FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY worker/ worker/
COPY api/schemas.py api/schemas.py
COPY api/config.py api/config.py
CMD ["python", "worker/worker.py"]
